# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: de.icr.io/ammbra/hangman-fed
  tag: 1
  pullSecret: regsecret
  pullPolicy: Always


backend:
  hostname: hangman
  port: 30001


replicaCount: 1

service:
  ports:
    port: 3000
    nodePort: 30002
  type: NodePort

ingress:
  enabled: false