apiVersion: v1
kind: Service
metadata:
  name: {{ include "fed.fullname" . }}
  labels:
    {{- include "fed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "fed.selectorLabels" . | nindent 4 }}
