apiVersion: v1
kind: Service
metadata:
  name: {{ include "hangman-fed.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hangman-fed.name" . }}
    helm.sh/chart: {{ include "hangman-fed.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      nodePort: {{ .Values.service.ports.nodePort}}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hangman-fed.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
