# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: ammbra/hangman
  tag: 0.0.1
  pullSecret: regsecret
  pullPolicy: Always

test:
  path: /api/admin


replicaCount: 1

readinessProbe:
  path: /api/actuator/info
  initialDelaySeconds: 20
  timeoutSeconds: 2
  periodSeconds: 3
  failureThreshold: 1


livenessProbe:
  path: /api/actuator/health
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 8
  failureThreshold: 1

service:
  ports:
    port: 8080
    nodePort: 30011
  type: NodePort

ingress:
  enabled: false